apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
    - name: Loki
      type: loki
      access: proxy
      orgId: 1
      url: http://loki:3100
      isDefault: true
      editable: true
---
apiVersion: v1
kind: Pod
metadata:
  name: grafana
  labels:
    app: grafana
spec:
  containers:
  - name: grafana
    image: grafana/grafana:10.2.2-ubuntu
    ports:
      - containerPort: 3000
    volumeMounts:
      - name: grafana-config-volume
        mountPath: /etc/grafana/provisioning/datasources
  volumes:
    - name: grafana-config-volume
      configMap:
        name: grafana-config
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
spec:
  ports:
  - port: 3000
    targetPort: 3000
    name: http
  selector:
    app: grafana
