apiVersion: v1
kind: Pod
metadata:
  name: cfs-mount-spinner
spec:
  containers:
    - name: myapp-container
      image: busybox:1.28
      command: ['sh', '-c', 'while true; do echo $(date); sleep 1; done']
      volumeMounts:
      - mountPath: /output
        name: output
  volumes:
  - hostPath:
      path: /data/17/job/522/output
      type: ""
    name: output