apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ssh://git@github.com/kubeflow/manifests.git///apps/jupyter/notebook-controller/upstream/base
configMapGenerator:
- name: config
  behavior: merge
  literals:
  - USE_ISTIO=true
  - ISTIO_GATEWAY=default/shared-gateway
