apiVersion: kubeflow.org/v1
kind: Notebook
metadata:
  name: notebook-sample
spec:
  config:
    subUrl: "/sample"
  template:
    spec:
      containers:
        - name: notebook-sample
          image: kubeflownotebookswg/jupyter:v1.6.0-rc.0
