# From:
# https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#components
apiVersion: v1
kind: Service
metadata:
  name: volume-claim-retain-test
  labels:
    app: volume-claim-retain-test
spec:
  ports:
    - port: 80
      name: web
  clusterIP: None
  selector:
    app: volume-claim-retain-test
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: volume-claim-retain-test
spec:
  selector:
    matchLabels:
      app: volume-claim-retain-test
  serviceName: "volume-claim-retain-test"
  replicas: 1
  template:
    metadata:
      labels:
        app: volume-claim-retain-test
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: nginx
          image: registry.k8s.io/nginx-slim:0.8
          ports:
            - containerPort: 80
              name: web
          volumeMounts:
            - name: www
              mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
    - metadata:
        name: www
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "ebs-ssd"
        resources:
          requests:
            storage: 20Gi