apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      access: proxy
      orgId: 1
      url: http://localhost:9090
      isDefault: true
      editable: true
---
apiVersion: v1
kind: Pod
metadata:
  name: prometheus-grafana-pod
spec:
  containers:
  - name: prometheus
    image: prom/prometheus:latest
    ports:
      - containerPort: 9090
  - name: grafana
    image: grafana/grafana:latest
    ports:
      - containerPort: 3000
    volumeMounts:
      - name: grafana-config-volume
        mountPath: /etc/grafana/provisioning/datasources
  volumes:
    - name: grafana-config-volume
      configMap:
        name: grafana-config
