datasources:
 datasources.yaml:
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      access: proxy
      orgId: 1
      url: http://prometheus-server  # from chart prometheus-community/prometheus --version 25.8.0
      isDefault: true
      editable: true
    - name: Loki
      type: loki
      access: proxy
      orgId: 1
      url: http://loki:3100
      editable: true
adminPassword: admin

grafana.ini:
  # # Only allow anonymous authentication
  # auth:
  #   disable_login_form: true
  auth.anonymous:
    enabled: true
    org_name: Main Org.
    org_role: Viewer
    hide_version: true
