apiVersion: v1
kind: Pod
metadata:
  name: simple-log-generator
spec:
  containers:
    - name: myapp-container
      image: busybox:1.28
      command:
      - '/bin/sh'
      - '-c'
      - |
        while true; do echo $(date); sleep 1; done