apiVersion: v1
kind: Pod
metadata:
  name: nfs-spinner
spec:
  containers:
    - name: myapp-container
      image: ubuntu
      command:
        - "/bin/sh"
        - "-c"
        - |
          while true; do echo $(date); sleep 1; done
      securityContext:
        allowPrivilegeEscalation: true
        capabilities: {}
        privileged: true
        readOnlyRootFilesystem: false
        runAsNonRoot: false
# apt-get update
# apt-get -y install nfs-kernel-server rpcbind
# service rpcbind start
# service nfs-common start
# mount -t nfs xxxx
