apiVersion: "kubeflow.org/v1"
kind: PyTorchJob
metadata:
  name: pytorchjob-v1
  namespace: kubeflow
spec:
  runPolicy:
    cleanPodPolicy: None
    activeDeadlineSeconds: 1800 # if the pytorch job won't become active after this 30min,
  pytorchReplicaSpecs:
    Master:
      replicas: 1
      restartPolicy: Never # set the pytorch job never restart
      template:
        spec:
          containers:
            - name: pytorch
              image: docker.io/kubeflowkatib/pytorch-mnist:v1beta1-45c5727
              imagePullPolicy: Always
              command: ["/bin/sh","-c"]
              args:
                # So slow to download a large gz file from s3
                - python3 /opt/pytorch-mnist/mnist.py --epochs=1
