apiVersion: v1
kind: Pod
metadata:
  name: istio-crd-checker
spec:
  serviceAccountName: istio-crd-checker
  containers:
    - name: myapp-container
      image: ubuntu:22.04
      command:
        - '/bin/sh'
        - '-c'
        - |
          while true; do echo $(date); sleep 1; done
