apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: istio-crd-checker
rules:
  - apiGroups:
      - security.istio.io
    resources:
      - requestauthentications
      - authorizationpolicies
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: istio-crd-checker
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: istio-crd-checker
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: istio-crd-checker
subjects:
  - kind: ServiceAccount
    name: istio-crd-checker
    namespace: default
