apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: storage-monitor
spec:
  containers:
    - name: storage-monitor
      image: python:3.10-slim-bullseye
      volumeMounts:
        - name: data
          mountPath: /data
      command:
        - "/bin/sh"
        - "-c"
        - |
          while true; do echo $(date); sleep 1; done
  restartPolicy: OnFailure
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: data-pvc
