apiVersion: v1
kind: Pod
metadata:
  name: simple-log-generator-with-tag
  labels:
    platform.colossalai.com/podtype: pytorchjob
spec:
  containers:
    - name: myapp-container
      image: busybox:1.28
      command: ['sh', '-c', 'while true; do echo $(date); sleep 1; done']
