apiVersion: v1
kind: Pod
metadata:
  name: huggingface-downloader
  labels:
    app: huggingface-downloader
spec:
  containers:
    - name: app
      image: python:bullseye
      command: ['sh', '-c', 'while true; do echo $(date); sleep 1; done']
