apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tos-tensorboard-230608
  namespace: kubeflow-user-example-com
spec:
#  storageClassName: ""  # 假如配置了 default 的 StorageClass，将会失败。
  accessModes:  # PVC 访问模式。目前仅支持 ReadWriteMany ，表示多点读写。
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi  # 声明的存储使用量。
  volumeMode: Filesystem # 挂载对象存储的格式，本示例填写 Filesystem，表示文件系统挂载。
  volumeName: tos-tensorboard-230608  # 绑定到该 PVC 的 PV 名称。
