# This yaml demonstrates how to wait for a daemonset until it starts,
# by setting `initContainers` field.
apiVersion: v1
kind: Pod
metadata:
  name: tos-tensorboard-230608
spec:
  containers:
    - name: myapp-container
      image: busybox:1.28
      command: ['sh', '-c', 'while true; do echo $(date); sleep 1; done']
      volumeMounts:
        - mountPath: "/tmp/tos-yaml-230605"
          name: data
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: tos-tensorboard-230608
