apiVersion: v1
kind: Pod
metadata:
  name: mongo-express-manual-test
spec:
  containers:
    - name: mongo 
      image: mongo-express:0.54.0
      env:
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME
          value: root
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD
          value: example
        - name: ME_CONFIG_MONGODB_URL
          value: mongodb://root:example@supporting-service-mongodb-headless:27017/

