apiVersion: v1
kind: Pod
metadata:
  name: grpcurl-pod
spec:
  containers:
    - name: myapp-container
      image: fullstorydev/grpcurl:v1.8.9-alpine
      command:
        - "/bin/sh"
        - "-c"
        - |
          while true; do echo $(date); sleep 1; done
