apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: request-authentication
spec:
  selector:
    matchLabels:
      istio: ingressgateway
  jwtRules:
  - issuer: http://keycloak.default.svc.cluster.local:8080/realms/myrealm
    jwksUri: http://keycloak.default.svc.cluster.local:8080/realms/myrealm/protocol/openid-connect/certs
    forwardOriginalToken: true
---
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: reject-no-token-req
spec:
  selector:
    matchLabels:
      istio: ingressgateway
  action: DENY
  rules:
  - from:
    - source:
        notRequestPrincipals: ["*"]
