apiVersion: security.istio.io/v1
kind: RequestAuthentication
metadata:
  name: request-visualizer
  namespace: istio-system
spec:
  selector:
    matchLabels:
      app: request-visualizer
#      istio: ingressgateway # use Istio default gateway implementation
  jwtRules:
    - issuer: "ofey404@test.com"
      jwks: |
        {
          "keys": [
            {
              "kty": "RSA",
              "n": "mmO0OvOPQ53HRxV4eHOkTTxLVfk6zcq8KAD86gbnydYBNO_Si4Q1twyvefd58-BaO4N4NCEA97QrYm57ThKCe8agLGwWPHhxgbu_SAuYQehXxkf4sWy7Q17kGFG5k5AfQGZBqTY-YaawQqLlF6ILVbWab_AoEF4yB7pI3AnNnXs",
              "e": "AQAB",
              "d": "RzsrI2vONJcuIyjPzVslehEQfRkhPWOFTjuudNc8yA25vs_LZ11XXx42M-KvXIqtdvngUsTLan2w6pgowcuecX3t_2wUx0GJJgARfkN7gsWIS3CyXZBEEMjLGVU4vHt5zNE3GJKo3hb1TwEiulpL_Ix6hfcTSJpEaBWrBxjxV-E",
              "p": "5EA0bi6ui1H1wsG85oc7i9O7UH58WPIK_ytzBWXFIwcaSFFBqqNYNnZaHFsMe4cbHSBgShWHO3UueGVgOKmB8Q",
              "q": "rSi7CosQZmj_RFIYW10ef7XTZsdpIdOXV9-1dThAJUvkslKiTfdU7T0IYYsJ2K58ekJqdpcoKAVLB2SZVvdqKw",
              "dp": "S9yjEHPng1qsShzGQgB0ZBbtTOWdQpq_2OuCAStACFJWA-8t2h8MNJ3FeWMxlOTkuBuIpVbeaX6bAV0ATBTaoQ",
              "dq": "ZssMJhkh1jm0d-FoVix0Y4oUAiqUzaDnciH6faiz47AnBnkporEV-HPH2ugII1qJyKZOvzHCg-eIf84HfWoI2w",
              "qi": "lyVz1HI2b1IjzOMENkmUTaVEO6DM6usZi3c3_MobUUM05yyBhnHtPjWzqWn1uJ_Gt5bkJDdcpfvmkPAhKWEU9Q"
            }
          ]
        }
---
# reject requests without a JWT
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: request-visualizer-reject-no-token
  namespace: istio-system
spec:
  selector:
    matchLabels:
      app: request-visualizer
  action: DENY
  rules:
    - from:
        - source:
            notRequestPrincipals: ["*"]
---
# accept only selected one
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: request-visualizer-accept-only-certain-user
  namespace: istio-system
spec:
  selector:
    matchLabels:
      app: request-visualizer
  action: ALLOW
  rules:
    - from:
        - source:
            requestPrincipals: #  <ISS>/<SUB>
              - random/allowed-user