apiVersion: v1
kind: Pod
metadata:
  name: tos-yaml-230605
spec:
  containers:
    - name: myapp-container
      image: busybox:1.28
      command: ['sh', '-c', 'while true; do echo $(date); sleep 1; done']
      volumeMounts:
        - mountPath: "/tmp/tos-yaml-230605"
          name: tos-yaml-230605
  volumes:
    - name: tos-yaml-230605
      persistentVolumeClaim:
        claimName: tos-yaml-230605
