apiVersion: v1
kind: Pod
metadata:
  name: mongo-shell-spinner
spec:
  containers:
    - name: mongo 
      image: mongo:6.0.5
      command: ['sh', '-c', 'while true; do echo $(date); sleep 1; done']

