apiVersion: v1
kind: Pod
metadata:
  name: ssh-multiplex-2
  labels:
    app: ssh-multiplex-2
  annotations:
    sidecar.istio.io/inject: "false" # TODO
spec:
  containers:
  - name: openssh-server
    image: lscr.io/linuxserver/openssh-server:9.3_p2-r0-ls136
    ports:
    - containerPort: 2222
    env:
    - name: PUID
      value: "1000"
    - name: PGID
      value: "1000"
    - name: TZ
      value: "Etc/UTC"
    - name: SUDO_ACCESS
      value: "false"
    - name: PASSWORD_ACCESS
      value: "true"
    - name: USER_PASSWORD
      value: "password"
    - name: USER_NAME
      value: "username"
---
apiVersion: v1
kind: Service
metadata:
  name: ssh-multiplex-2
  labels:
    app: ssh-multiplex-2
spec:
  ports:
  - port: 2222
    name: ssh
  clusterIP: None  # A headless service
  selector:
    app: ssh-multiplex-2
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: ssh-multiplex-2
spec:
  hosts:
  - "*"
  gateways:
  - default/ssh-multiplex-gateway
  tcp:
  - route:
    - destination:
        host: ssh-multiplex-2.default.svc.cluster.local
        port:
          number: 2222

