apiVersion: v1
kind: Pod
metadata:
  name: nginx-logging-pod
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
      volumeMounts:
        - name: log-volume
          mountPath: /var/log/nginx
        - name: config-volume
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
  volumes:
    - name: log-volume
      emptyDir: {}
    - name: config-volume
      configMap:
        name: nginx-config
