apiVersion: v1
kind: Pod
metadata:
  name: my-secret-mounter
spec:
  containers:
    - name: myapp-container
      image: busybox:1.28
      command: ['sh', '-c', 'while true; do echo $(date); sleep 1; done']
      volumeMounts:
        - name: cred
          mountPath: /etc/cred
  volumes:
    # secret as volume
    - name: cred
      secret:
        secretName: my-secret
