apiVersion: v1
kind: Pod
metadata:
  name: kafka-tester
spec:
  containers:
    - name: kafkacat
      image: edenhill/kcat:1.7.1
      command: ['/bin/sh', '-c', 'while true; do echo $(date); sleep 1; done']
