apiVersion: v1
kind: Pod
metadata:
  name: cfs-append-experiment-writer-spinner
spec:
  containers:
    - name: writer
      image: cloud-platform-registry-cn-beijing.cr.volces.com/disposable-experiments/tensorboard-output-generator:latest
      command: ['sh', '-c', 'while true; do echo $(date); sleep 1; done']
      volumeMounts:
        - mountPath: /root/runs
          name: cfs
        - mountPath: /root/runs-no-cfs
          name: no-cfs
  volumes:
    - name: cfs
      hostPath:
        path: /data/tmp-cfs-append-experiment
    - name: no-cfs
      hostPath:
        path: /tmp/no-cfs
