apiVersion: v1
kind: ConfigMap
metadata:
  name: oauth2-proxy-alpha
  labels:
    app: oauth2-proxy
data:
  oauth2_proxy.yml: |-
    injectResponseHeaders:
      - name: kubeflow-userid
        values:
        - claim: email
    metricsServer:
      BindAddress: 0.0.0.0:44180
      SecureBindAddress: ""
      TLS: null
    providers:
    # ==== Keycloak configuration
    - id: keycloak-oidc
      clientID: myclient
      clientSecretFile: /etc/oauth2_proxy/CLIENT_SECRET
      provider: oidc
      loginURL: /auth/realms/myrealm/protocol/openid-connect/auth
      scope: openid profile email
      redeemURL: http://keycloak.default.svc.cluster.local/auth/realms/myrealm/protocol/openid-connect/token
      oidcConfig:
        audienceClaims:
        - azp
        emailClaim: email
        insecureAllowUnverifiedEmail: true
        issuerURL: http://localhost/auth/realms/myrealm
        jwksURL: http://keycloak.default.svc.cluster.local/auth/realms/myrealm/protocol/openid-connect/certs
        skipDiscovery: true
        userIDClaim: email

    server:
      BindAddress: 0.0.0.0:8080
      SecureBindAddress: ""
      TLS: null
    upstreamConfig:
      upstreams:
      - id: static://200
        path: /
        static: true
        staticCode: 200
binaryData: {}
